language: python
python:
 - "3.6"
dist: bionic
install:
 - pip install coverage
 - ./install
script:
 - gadma --test
 - coverage run -m unittest discover -t .
after_success:
 - bash <(curl -s https://codecov.io/bash)
