language: python
python:
 - "3.6"
dist: bionic
install:
 - pip install coverage
 - pip install codecov
 - ./install
script:
 - nosetests -vs tests --with-coverage --cover-package stdpopsim maintenance \
    --cover-branches --cover-erase --cover-xml --cover-inclusive tests
 - python3 -m codecov
after_success:
 - bash <(curl -s https://codecov.io/bash)
