language: python
python:
 - "3.6"
install:
 - pip3 install --upgrade pip
 - pip install --upgrade setuptools
 - chmod +x install
 - ./install
script:
 - gadma --test
 - python -m unittest discover -t .
