# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install dependencies.
        run: |
          pip install coverage
          pip install codecov
          pip install pycodestyle
          pip install GPy
          pip install GPyOpt
          pip install pandas

      - name: Install GADMA.
        run: |
          ./install
          cat gadma/version.py

      - name: Check code style.
        run: pycodestyle gadma

      - name: Run tests and codecov.
        run: |
          nosetests -vs tests --with-coverage --cover-package gadma     --cover-branches --cover-erase --cover-xml --cover-inclusive tests
          python3 -m codecov
          bash <(curl -s https://codecov.io/bash)
        

